name: Continuous Integration
on:
  pull_request:
jobs:
  build:
    name: building ogit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.17' ]

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - run: go version

    - name: Run test
      run: make
      shell: bash
